"#version 100\n"
"precision mediump float; \n"
"uniform vec4 nv_waveworks_impl_0_1; \n"
"uniform vec4 nv_waveworks_impl_0_2;\n"
"uniform vec4 nv_waveworks_impl_0_3;\n"
"uniform vec4 nv_waveworks_impl_0_4;\n"
"uniform vec4 nv_waveworks_impl_0_5;\n"
"uniform sampler2D nv_waveworks_impl_0_7;\n"
"varying vec2 nv_waveworks_impl_0_8;\n"
"attribute vec4 nv_waveworks_impl_0_9;\n"
"attribute vec2 nv_waveworks_impl_0_10;\n"
"void main()\n"
"{\n"
"    gl_Position = nv_waveworks_impl_0_9;\n"
"    nv_waveworks_impl_0_8 = nv_waveworks_impl_0_10;\n"
"}\n"
