"#version 150\n"
"\t\n"
"\t\n"
"\t\n"
"\t\n"
"\t\n"
"\t\n"
"\t\n"
"\t\n"
"\t\n"
"\tvec3 mul(vec4 v, mat3x4 m) { return v * m; }\n"
"\t\n"
"\t\n"
"uniform vec4 nv_waveworks_impl_0_1; \n"
"uniform vec4 nv_waveworks_impl_0_2;\n"
"uniform vec4 nv_waveworks_impl_0_3;\n"
"uniform vec4 nv_waveworks_impl_0_4;\n"
"uniform vec4 nv_waveworks_impl_0_5;\n"
"uniform sampler2D nv_waveworks_impl_0_7;\n"
"out vec2 nv_waveworks_impl_0_8;\n"
"in vec4 nv_waveworks_impl_0_9;\n"
"in vec2 nv_waveworks_impl_0_10;\n"
"void main()\n"
"{\n"
"    gl_Position = nv_waveworks_impl_0_9;\n"
"    nv_waveworks_impl_0_8 = nv_waveworks_impl_0_10;\n"
"}\n"
