LPCTSTR kVesselConfigString =
	L"Mesh .\\Media\\boat.sdkmesh\n"
	L"DiffuseGamma 2.2\n"
	L"Length 69\n"
	L"CameraHeightAboveWater 12.85\n"
	L"CameraLongitudinalOffset 10.35\n"
	L"AttitudeInDegrees 1.35\n"
	L"HeightDrag 1\n"
	L"PitchDrag 2\n"
	L"YawDrag 0.5\n"
	L"YawCoefficient 0.5\n"
	L"RollDrag 1\n"
	L"MetacentricHeight 0.8\n"
	L"HullProfileTextureWH 1024\n"
	L"\n"
	L"LongitudinalCOM -3.0\n"
	L"InitialHeight -0.85\n"
	L"InitialPitch 0.013\n"
	L"\n"
	L"PitchInertiaMult 0.4\n"
	L"\n"
	L"FunnelLongitudinalOffset -3.9\n"
	L"FunnelHeightAboveWater 9.6\n"
	L"FunnelXSize 0.4\n"
	L"FunnelYSize 0.1\n"
	L"\n"
	L"SmokeTexture .\\Media\\smoke.dds\n"
	L"NumSmokeParticles 100000\n"
	L"SmokeEmitMinVelocity 15\n"
	L"SmokeEmitMaxVelocity 20\n"
	L"SmokeEmitSpread 0.25\n"
	L"SmokeEmitRate 10000\n"
	L"SmokeParticleBeginSize 0.3\n"
	L"SmokeParticleEndSize 1.0\n"
	L"SmokeWindDrag 5.0\n"
	L"SmokeMinBuoyancy 4.0\n"
	L"SmokeMaxBuoyancy 5.0\n"
	L"SmokeCoolingRate 0.1\n"
	L"\n"
	L"PSMMinCornerX -50.0\n"
	L"PSMMaxCornerX  50.0\n"
	L"PSMMinCornerY -100.0\n"
	L"PSMMaxCornerY  50.0\n"
	L"PSMMinCornerZ -40.0\n"
	L"PSMMaxCornerZ  40.0\n"
	L"PSMRes 512\n"
	L"\n"
	L"SmokePSMBoundsFadeMargin 0.1\n"
	L"SmokeShadowOpacity 0.2\n"
	L"SmokeWindNoiseSpatialScale 0.25\n"
	L"SmokeWindNoiseTimeScale 5.0\n"
	L"SmokeWindNoiseLevel 1.5\n"
	L"SmokeTintR 1.0\n"
	L"SmokeTintG 1.1\n"
	L"SmokeTintB 1.3\n"
	L"\n"
	L"NumSurfaceHeightSamples 3000\n"
	L"\n"
	L"BeginSpotlight\n"
	L"x 0\n"
	L"y 20\n"
	L"z 21\n"
	L"axis-x 0\n"
	L"axis-y -1\n"
	L"axis-z 0.5\n"
	L"r 200\n"
	L"g 150\n"
	L"b 50\n"
	L"beam_angle 75\n"
	L"EndSpotlight\n"
	L"\n"
	L"BeginSpotlight\n"
	L"x 3.25\n"
	L"y 7\n"
	L"z 7\n"
	L"axis-x 0.2\n"
	L"axis-y -1\n"
	L"axis-z 0.25\n"
	L"r 20\n"
	L"g 15\n"
	L"b 5\n"
	L"beam_angle 90\n"
	L"EndSpotlight\n"
	L"\n"
	L"BeginSpotlight\n"
	L"x -3.25\n"
	L"y 7\n"
	L"z 7\n"
	L"axis-x -0.2\n"
	L"axis-y -1\n"
	L"axis-z 0.25\n"
	L"r 20\n"
	L"g 15\n"
	L"b 5\n"
	L"beam_angle 90\n"
	L"EndSpotlight\n"
	L"\n"
	L"BeginSpotlight\n"
	L"x 3.25\n"
	L"y 7\n"
	L"z 3\n"
	L"axis-x 0.2\n"
	L"axis-y -1\n"
	L"axis-z 0\n"
	L"r 20\n"
	L"g 15\n"
	L"b 5\n"
	L"beam_angle 90\n"
	L"EndSpotlight\n"
	L"\n"
	L"BeginSpotlight\n"
	L"x -3.25\n"
	L"y 7\n"
	L"z 3\n"
	L"axis-x -0.2\n"
	L"axis-y -1\n"
	L"axis-z 0\n"
	L"r 20\n"
	L"g 15\n"
	L"b 5\n"
	L"beam_angle 90\n"
	L"EndSpotlight\n"
	L"\n"
	L"BeginSpotlight\n"
	L"x 0\n"
	L"y 10\n"
	L"z -3\n"
	L"axis-x 0\n"
	L"axis-y 0\n"
	L"axis-z 1\n"
	L"r 20\n"
	L"g 15\n"
	L"b 5\n"
	L"beam_angle 90\n"
	L"EndSpotlight\n"
	L"\n"
	L"BeginSpotlight\n"
	L"x 3.25\n"
	L"y 5\n"
	L"z -17\n"
	L"axis-x 0.2\n"
	L"axis-y -1\n"
	L"axis-z 0\n"
	L"r 10\n"
	L"g 7.5\n"
	L"b 2.5\n"
	L"beam_angle 90\n"
	L"EndSpotlight\n"
	L"\n"
	L"BeginSpotlight\n"
	L"x -3.25\n"
	L"y 5\n"
	L"z -17\n"
	L"axis-x -0.2\n"
	L"axis-y -1\n"
	L"axis-z 0\n"
	L"r 10\n"
	L"g 7.5\n"
	L"b 2.5\n"
	L"beam_angle 90\n"
	L"EndSpotlight\n"
	L"\n"
	L"BeginSpotlight\n"
	L"x 3.25\n"
	L"y 5\n"
	L"z -20\n"
	L"axis-x 0.2\n"
	L"axis-y -1\n"
	L"axis-z -0.25\n"
	L"r 10\n"
	L"g 7.5\n"
	L"b 2.5\n"
	L"beam_angle 90\n"
	L"EndSpotlight\n"
	L"\n"
	L"BeginSpotlight\n"
	L"x -3.25\n"
	L"y 5\n"
	L"z -20\n"
	L"axis-x -0.2\n"
	L"axis-y -1\n"
	L"axis-z -0.25\n"
	L"r 10\n"
	L"g 7.5\n"
	L"b 2.5\n"
	L"beam_angle 90\n"
	L"EndSpotlight\n"
	L"\n"
	L"BeginSpotlight\n"
	L"x 0\n"
	L"y 5\n"
	L"z -22.5\n"
	L"axis-x 0\n"
	L"axis-y -1\n"
	L"axis-z -0.5\n"
	L"r 10\n"
	L"g 7.5\n"
	L"b 2.5\n"
	L"beam_angle 120\n"
	L"EndSpotlight\n"
	;
