FUNCTION(CompileFXToH FILE OUTPUT_DIR TARGET INCLUDE_DIR INCLUDE_DIR2 ENTRYPOINT OPTIONS)

	GET_FILENAME_COMPONENT(FILE_WE ${FILE} NAME_WE)
		
#	"/I${SHADER_SRC_DIR} /EGFSDK_WAVEWORKS_VERTEX_INPUT_Sig /Tvs_4_0 ${SHADER_SRC_DIR}\Quadtree_SM4_sig.fx /Fh ${WW_SOURCE_DIR}\generated\Quadtree_SM4_sig.h"
	
	ADD_CUSTOM_TARGET(${TARGET} ALL)
	
	ADD_CUSTOM_COMMAND(
		PRE_BUILD
#		TARGET ${TARGET}
		OUTPUT ${OUTPUT_DIR}/${FILE_WE}.h
		COMMAND ${DirectX_FXC_EXECUTABLE} /I${INCLUDE_DIR} /I${INCLUDE_DIR2} /E${ENTRYPOINT} ${OPTIONS} ${FILE} /Fh ${OUTPUT_DIR}/${FILE_WE}.h
		MAIN_DEPENDENCY ${FILE}
		COMMENT "FXC Compile ${FILE}"
		VERBATIM
	)
	
	#ADD_DEPENDENCIES(${TARGET} ${OUTPUT_DIR}/generated/${FILE_WE}.h)

ENDFUNCTION(CompileFXToH)
